### ISSUE TITLE
Some questions about how to use this project!

### ISSUE THREAD

**Issue by bigbigbanana** [TheJJ/x-tier#1]
Hi,recently i am doing researching on tracing system calls happend in vm,and i am interested in your project,but i don't know how to use it,is there any installtion guide like Nitro?

**Comment by TheJJ** [comment]
This project does not trace system calls via VMI. It uses ptrace to grab them.

nitro can be used for VMI syscall capturing, and there surely is some guide somewhere in this Internet. I haven't used nitro so far.

**Comment by bigbigbanana** [comment]
I want to know the installtion guide of your project because i don't get enough install information from your thesis,could u please write README in your project.Thanks.

**Comment by TheJJ** [comment]
I'm sorry but I don't have motivation to invest much time in this project right now.

The basic steps are:
* compile my QEMU fork
* compile my kernel fork
* compile this repo to get `lolredirect`.

Then, running works like this:

* Run my forked Linux on a bare-metal machine (=hypervisor)
* Run Linux in a VM in the forked QEMU
* Compile the injection kernel modules for the system map of the kernel of this VM
* Convert the injectionmodules so they are wrapped for injection and self-contained stack
* Use `lolredirect` to run a program and redirect its syscalls

I hope this helps.

**Comment by VPaulV** [comment]
Hi Sorry for the bump, could not get access to your X-Tier paper, so wanted to ask directly. Did X-Tier kernel modules work on vanilla KVM, or you had to patch QEMU/KVM first? (Basically KVMi)

**Comment by TheJJ** [comment]
kernel and qemu were patched :) but only for the host system. the vm where we inject the syscall is unmodified.
